export const GET_PLANT_REQ = "GET_PLANT_REQ";
export const GET_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const GET_PLANT_FAIL = "GET_PLANT_FAIL";


export const POST_PLANT_REQ = "GET_PLANT_REQ";
export const POST_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const POST_PLANT_FAIL = "GET_PLANT_FAIL";


export const ADD_TO_CART_REQ = "ADD_TO_CART_REQ";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";


export const GET_CART_REQ = "GET_CART_REQ";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const GET_All_PLANTS_REQ = "GET_All_PLANTS_REQ";
export const GET_All_PLANTS_SUCCESS = "GET_All_PLANTS_SUCCESS";
export const GET_All_PLANTS_FAIL = "GET_All_PLANTS_FAIL";