const GET_PLANT_REQ = "GET_PLANT_REQ";
const GET_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
const GET_PLANT_FAIL = "GET_PLANT_FAIL";


const POST_PLANT_REQ = "GET_PLANT_REQ";
const POST_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
const POST_PLANT_FAIL = "GET_PLANT_FAIL";