export const GET_PLANT_REQ = "GET_PLANT_REQ";
export const GET_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const GET_PLANT_FAIL = "GET_PLANT_FAIL";


export const POST_PLANT_REQ = "GET_PLANT_REQ";
export const POST_PLANT_SUCCESS = "GET_PLANT_SUCCESS";
export const POST_PLANT_FAIL = "GET_PLANT_FAIL";


export const ADD_TO_CART_REQ = "ADD_TO_CART_REQ";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";